const icon=(bg,body)=>`<svg viewBox="0 0 64 64" aria-hidden="true"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${bg[0]}"/><stop offset="1" stop-color="${bg[1]}"/></linearGradient></defs><rect x="4" y="4" width="56" height="56" rx="16" fill="url(#g)"/>${body}</svg>`;
const icons={
 shopping:icon(['#a855f7','#5b21b6'],'<path d="M18 25h28l-2.5 23h-23z" fill="#fff"/><path d="M24 26v-3a8 8 0 0 1 16 0v3" fill="none" stroke="#fff" stroke-width="4" stroke-linecap="round"/><path d="M26 35h12" stroke="#7c3aed" stroke-width="3.5" stroke-linecap="round"/>'),
 digitacao:icon(['#2dd4bf','#0f766e'],'<rect x="13" y="19" width="38" height="27" rx="6" fill="#fff"/><g fill="#0f766e"><rect x="18" y="24" width="5" height="4" rx="1"/><rect x="26" y="24" width="5" height="4" rx="1"/><rect x="34" y="24" width="5" height="4" rx="1"/><rect x="42" y="24" width="4" height="4" rx="1"/><rect x="18" y="31" width="5" height="4" rx="1"/><rect x="26" y="31" width="5" height="4" rx="1"/><rect x="34" y="31" width="5" height="4" rx="1"/><rect x="42" y="31" width="4" height="4" rx="1"/><rect x="22" y="38" width="22" height="4" rx="2"/></g>'),
 leitor:icon(['#fbbf24','#b45309'],'<path d="M16 18c7-2 12 0 16 4v28c-4-4-9-6-16-4zM48 18c-7-2-12 0-16 4v28c4-4 9-6 16-4z" fill="#fff"/><path d="M32 22v28" stroke="#f59e0b" stroke-width="2"/>'),
 iptv:icon(['#fb7185','#be123c'],'<rect x="13" y="17" width="38" height="28" rx="7" fill="#fff"/><path d="M28 25l11 7-11 7z" fill="#e11d48"/><path d="M24 50h16" stroke="#fff" stroke-width="4" stroke-linecap="round"/>'),
 jogos:icon(['#f472b6','#be185d'],'<path d="M21 24h22c5 0 8 4 9 10l2 10c1 6-5 9-9 5l-6-6H25l-6 6c-4 4-10 1-9-5l2-10c1-6 4-10 9-10z" fill="#fff"/><path d="M22 31v10M17 36h10" stroke="#db2777" stroke-width="3" stroke-linecap="round"/><circle cx="42" cy="33" r="2.5" fill="#db2777"/><circle cx="47" cy="38" r="2.5" fill="#db2777"/>'),
 encontrapet:icon(['#fb923c','#ea580c'],'<ellipse cx="32" cy="39" rx="10" ry="8" fill="#fff"/><circle cx="20" cy="29" r="5" fill="#fff"/><circle cx="28" cy="23" r="5" fill="#fff"/><circle cx="36" cy="23" r="5" fill="#fff"/><circle cx="44" cy="29" r="5" fill="#fff"/>'),
 vendezap:icon(['#4ade80','#15803d'],'<path d="M17 20h21l10 10-21 21-10-10z" fill="#fff"/><circle cx="31" cy="28" r="3" fill="#16a34a"/><path d="M27 40h13M33 34v12" stroke="#16a34a" stroke-width="3" stroke-linecap="round"/>'),
 admin:icon(['#64748b','#1e293b'],'<rect x="14" y="17" width="36" height="30" rx="6" fill="#fff"/><rect x="19" y="22" width="12" height="8" rx="2" fill="#334155"/><rect x="34" y="22" width="11" height="8" rx="2" fill="#94a3b8"/><rect x="19" y="34" width="26" height="3" rx="1.5" fill="#64748b"/><rect x="19" y="40" width="18" height="3" rx="1.5" fill="#cbd5e1"/>'),
 sobre:icon(['#60a5fa','#1d4ed8'],'<rect x="13" y="17" width="38" height="26" rx="6" fill="#fff"/><path d="M23 50h18M28 43v7M36 43v7" stroke="#fff" stroke-width="3" stroke-linecap="round"/><path d="M20 25l5 10 6-10 6 10 7-10" fill="none" stroke="#2563eb" stroke-width="3.2" stroke-linecap="round" stroke-linejoin="round"/>'),
 contato:icon(['#475569','#111827'],'<path d="M15 19h34v25H31l-10 7v-7h-6z" fill="#fff"/><circle cx="24" cy="32" r="2.4" fill="#334155"/><circle cx="32" cy="32" r="2.4" fill="#334155"/><circle cx="40" cy="32" r="2.4" fill="#334155"/>')
};
const apps={
 shopping:{title:'WDM Shopping',label:'Shopping',url:'https://wdmapps.com.br/shopping/',icon:'shopping',mode:'iframe'},
 digitacao:{title:'WDM Digitação',label:'Digitação',url:'https://wdmapps.com.br/digitacao/',icon:'digitacao',mode:'iframe'},
 leitor:{title:'WDM Leitor',label:'Leitor',url:'https://wdmapps.com.br/leitor/',icon:'leitor',mode:'iframe'},
 iptv:{title:'WDM IPTV',label:'IPTV',url:'https://wdmapps.com.br/iptv/',icon:'iptv',mode:'iframe'},
 jogos:{title:'Jogos WDM',label:'Jogos',url:'https://wdmapps.com.br/jogos/',icon:'jogos',mode:'iframe'},
 encontrapet:{title:'EncontraPet',label:'EncontraPet',url:'https://play.google.com/store/apps/details?id=com.wdmapps.encontrapet',icon:'encontrapet',mode:'external',description:'Rede solidária para divulgar animais perdidos e ajudar no reencontro com suas famílias.'},
 vendezap:{title:'VendeZap',label:'VendeZap',url:'https://play.google.com/store/apps/details?id=com.will.vendezap',icon:'vendezap',mode:'external',description:'Crie anúncios de forma rápida e compartilhe direto pelo WhatsApp.'},
 admin:{title:'Admin WDM',label:'Admin',url:'https://wdmapps.com.br/admin/',icon:'admin',mode:'iframe'},
 sobre:{title:'WDM Apps',label:'Sobre a WDM',url:'https://wdmapps.com.br/',icon:'sobre',mode:'external',description:'Aplicativos, sites e sistemas criados pela WDM Apps.'},
 contato:{title:'Contato WDM',label:'Contato',url:'https://wa.me/5511969188837?text=Ol%C3%A1%2C%20vim%20pelo%20site%20da%20WDM%20Apps.',icon:'contato',mode:'external',description:'Fale direto com a WDM Apps pelo WhatsApp.'}
};
const desktopIcons=document.getElementById('desktopIcons'),pinGrid=document.getElementById('pinGrid'),running=document.getElementById('running'),desktop=document.getElementById('desktop'),startMenu=document.getElementById('startMenu'),startBtn=document.getElementById('startBtn');
const iconHtml=(name,cls='app-icon')=>`<span class="${cls}">${icons[name]}</span>`;
Object.entries(apps).forEach(([key,app])=>{const d=document.createElement('button');d.className='desktop-icon';d.dataset.open=key;d.innerHTML=iconHtml(app.icon)+`<span class="label">${app.label}</span>`;desktopIcons.appendChild(d);const p=document.createElement('button');p.className='pin';p.dataset.open=key;p.innerHTML=iconHtml(app.icon)+`<span>${app.label}</span>`;pinGrid.appendChild(p)});
let z=30,cascade=0;const openWindows=new Map();
function taskButton(id,app){const b=document.createElement('button');b.className='task-app active';b.dataset.task=id;b.title=app.title;b.innerHTML=iconHtml(app.icon);b.onclick=()=>toggleMinimize(id);running.appendChild(b);return b}
function setActive(id){document.querySelectorAll('.task-app').forEach(b=>b.classList.remove('active'));document.querySelector(`[data-task="${id}"]`)?.classList.add('active')}
function focusWindow(win,id){win.style.zIndex=++z;setActive(id)}
function makeWindow(appKey){const app=apps[appKey];if(openWindows.has(appKey)){const d=openWindows.get(appKey);d.win.classList.remove('hidden');focusWindow(d.win,appKey);return}const win=document.createElement('section');win.className='window';const offset=(cascade++%7)*26;win.style.left=180+offset+'px';win.style.top=70+offset+'px';win.style.zIndex=++z;win.dataset.id=appKey;const body=app.mode==='iframe'?`<div class="browserview"><div class="loading">Carregando ${app.title}...</div><iframe src="${app.url}" title="${app.title}" loading="eager"></iframe></div>`:`<div class="browserview"><div class="external-card"><div class="external-panel"><div class="big-icon">${icons[app.icon]}</div><h2>${app.title}</h2><p>${app.description||''}</p><a href="${app.url}" target="_blank" rel="noreferrer">Abrir ${app.label} ↗</a></div></div></div>`;win.innerHTML=`<div class="titlebar"><span class="app-mini">${icons[app.icon]}</span><strong>${app.title}</strong><div class="controls"><button class="min" title="Minimizar">—</button><button class="max" title="Maximizar">□</button><button class="close" title="Fechar">×</button></div></div><div class="browserbar"><button class="browserbtn" title="Voltar">←</button><button class="browserbtn" title="Avançar">→</button><button class="browserbtn reload" title="Atualizar">↻</button><div class="address"><span class="lock">🔒</span><span>${app.url}</span></div><button class="open-external">Abrir fora ↗</button></div>${body}`;desktop.appendChild(win);const task=taskButton(appKey,app);openWindows.set(appKey,{win,task});const iframe=win.querySelector('iframe');if(iframe){iframe.addEventListener('load',()=>win.querySelector('.loading')?.classList.add('hide'));win.querySelector('.reload').onclick=()=>{win.querySelector('.loading')?.classList.remove('hide');iframe.src=iframe.src}}win.querySelector('.open-external').onclick=()=>window.open(app.url,'_blank');win.querySelector('.min').onclick=()=>minimize(appKey);win.querySelector('.max').onclick=()=>{win.classList.toggle('maximized');focusWindow(win,appKey)};win.querySelector('.close').onclick=()=>closeWindow(appKey);win.addEventListener('mousedown',()=>focusWindow(win,appKey));makeDraggable(win,win.querySelector('.titlebar'),appKey)}
function minimize(id){const d=openWindows.get(id);if(!d)return;d.win.classList.add('hidden');d.task.classList.remove('active')}
function toggleMinimize(id){const d=openWindows.get(id);if(!d)return;if(d.win.classList.contains('hidden')){d.win.classList.remove('hidden');focusWindow(d.win,id);return}const visible=[...openWindows.values()].filter(x=>!x.win.classList.contains('hidden')),topZ=Math.max(...visible.map(x=>+(x.win.style.zIndex||0)),0);+(d.win.style.zIndex||0)===topZ?minimize(id):focusWindow(d.win,id)}
function closeWindow(id){const d=openWindows.get(id);if(!d)return;d.win.remove();d.task.remove();openWindows.delete(id)}
function makeDraggable(win,handle,id){let sx=0,sy=0,sl=0,st=0,drag=false;handle.addEventListener('mousedown',e=>{if(win.classList.contains('maximized')||e.target.closest('.controls'))return;drag=true;sx=e.clientX;sy=e.clientY;sl=win.offsetLeft;st=win.offsetTop;focusWindow(win,id);document.body.style.userSelect='none'});window.addEventListener('mousemove',e=>{if(!drag)return;let nl=sl+e.clientX-sx,nt=st+e.clientY-sy;nl=Math.max(0,Math.min(nl,innerWidth-win.offsetWidth));nt=Math.max(0,Math.min(nt,innerHeight-70));win.style.left=nl+'px';win.style.top=nt+'px'});window.addEventListener('mouseup',()=>{drag=false;document.body.style.userSelect=''})}
document.querySelectorAll('[data-open]').forEach(el=>{el.addEventListener('dblclick',()=>makeWindow(el.dataset.open));if(el.classList.contains('pin'))el.addEventListener('click',()=>{makeWindow(el.dataset.open);startMenu.classList.remove('show')});if(el.classList.contains('desktop-icon'))el.addEventListener('click',()=>{document.querySelectorAll('.desktop-icon').forEach(x=>x.classList.remove('selected'));el.classList.add('selected')})});
startBtn.onclick=e=>{e.stopPropagation();startMenu.classList.toggle('show')};document.addEventListener('click',e=>{if(!startMenu.contains(e.target)&&!startBtn.contains(e.target))startMenu.classList.remove('show')});
function updateClock(){const d=new Date();document.getElementById('time').textContent=d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});document.getElementById('date').textContent=d.toLocaleDateString('pt-BR')}updateClock();setInterval(updateClock,30000);