import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import { getAuth, onAuthStateChanged, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, deleteUser } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import { getFirestore, collection, doc, getDoc, getDocs, setDoc, updateDoc, deleteDoc, query, where, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';

const fb=initializeApp(firebaseConfig),auth=getAuth(fb),db=getFirestore(fb),app=document.getElementById('app');
const D=v=>String(v??'').replace(/\D/g,''),E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),pm=v=>{const d=D(v);return d?Number(d)/100:0};
function phone(v){let d=D(v);if(d.length>11&&d.startsWith('55'))d=d.slice(2);d=d.slice(0,11);if(!d)return'';if(d.length<=2)return`(${d}`;const a=d.slice(0,2),r=d.slice(2);if(d.length<=10)return`(${a}) ${r.slice(0,4)}${r.length>4?'-'+r.slice(4,8):''}`;return`(${a}) ${r.slice(0,1)}${r.length>1?' '+r.slice(1,5):''}${r.length>5?'-'+r.slice(5,9):''}`}
function wd(v){let d=D(v);if(d.length>11&&d.startsWith('55'))d=d.slice(2);return d.length>=10?'55'+d:d}
function slug(v){return String(v||'loja').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'loja'}
function initials(v){return String(v||'WS').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'WS'}
function msg(err){const c=err?.code||'';return ({'auth/email-already-in-use':'Este e-mail já está cadastrado.','auth/invalid-email':'Digite um e-mail válido.','auth/weak-password':'A senha precisa ter pelo menos 6 caracteres.','auth/invalid-credential':'E-mail ou senha inválidos.','auth/operation-not-allowed':'Ative E-mail/Senha no Firebase Authentication.','auth/too-many-requests':'Muitas tentativas. Tente novamente mais tarde.','permission-denied':'Operação bloqueada pelas regras do Firestore.','failed-precondition':'Crie o banco Cloud Firestore no Firebase Console.','unavailable':'Firebase temporariamente indisponível.'})[c]||err?.message||'Não foi possível concluir.'}
const samples=[['techmix','TechMix Informática','Tecnologia','TM','#20509a','Computadores, acessórios e manutenção.'],['casabela','Casa Bela','Casa','CB','#805234','Utilidades e decoração para sua casa.'],['sabordavila','Sabor da Vila','Alimentação','SV','#8a392f','Lanches, porções e combos preparados na hora.'],['urbanstyle','Urban Style','Moda','US','#4c3f82','Moda casual, acessórios e lançamentos.'],['studio47','Studio 47','Beleza','47','#316057','Cabelo, barba e estética com agendamento.'],['reparafacil','Repara Fácil','Serviços','RF','#73541f','Reparos, elétrica e manutenção residencial.']];
const svc=[['⚡','Eletricista'],['🎨','Pintor'],['🔧','Técnico de informática'],['🧱','Pedreiro']];
function nav(){const on=!!auth.currentUser;for(const id of ['accountTop','accountMobile']){const a=document.getElementById(id);if(!a)continue;a.href=on?'#painel':'#login';a.textContent=on?(id==='accountTop'?'Meu painel':'⚙ Painel'):(id==='accountTop'?'Área do lojista':'⚙ Lojista')}}
async function published(){try{const s=await getDocs(query(collection(db,'stores'),where('published','==',true)));return s.docs.map(d=>({id:d.id,...d.data()}))}catch(e){console.warn('Firestore ainda não pronto:',e.code);return[]}}
async function getStore(uid=auth.currentUser?.uid){if(!uid)return null;const s=await getDoc(doc(db,'stores',uid));return s.exists()?{id:s.id,...s.data()}:null}
async function getProducts(storeId,all=false){try{const ref=collection(db,'stores',storeId,'products'),s=all?await getDocs(ref):await getDocs(query(ref,where('active','==',true)));return s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>Number(b.featured)-Number(a.featured))}catch(e){console.warn('Produtos:',e.code);return[]}}
async function bySlug(id){try{const sl=await getDoc(doc(db,'slugs',id));if(!sl.exists())return null;const st=await getDoc(doc(db,'stores',sl.data().storeId));return st.exists()?{id:st.id,...st.data()}:null}catch(e){return null}}
function rid(s){return s.slug||s.id}

async function home(anchor=''){
 const custom=(await published()).map(s=>[rid(s),s.name,s.category,s.initials||initials(s.name),s.primary||'#2f7df6',s.description||'']);
 const stores=[...custom,...samples.filter(x=>!custom.some(c=>c[0]===x[0]))];
 app.innerHTML=`<section class="shell hero"><div><span class="ey">O comércio da sua cidade, conectado</span><h1>Encontre lojas, ofertas e profissionais <em>perto de você.</em></h1><p>Uma vitrine digital simples para quem compra e uma loja fácil de administrar para quem vende.</p><div class="search"><input id="q" placeholder="Buscar loja, produto ou serviço..."><button class="btn" id="go">Buscar</button></div><p><a class="btn" href="#cadastro">Quero minha loja</a></p></div><aside class="heroCard"><span class="ey">Destaque local</span><div class="fakeLogo">WS</div><h2>Sua loja pode estar aqui</h2><p>Cadastre produtos, promoções e receba pedidos direto no WhatsApp.</p></aside></section><section class="shell stats"><div><strong>24h</strong><span>vitrine disponível</span></div><div><strong>0%</strong><span>comissão nas vendas</span></div><div><strong>Firebase</strong><span>contas e dados online</span></div><div><strong>WhatsApp</strong><span>venda direto com a loja</span></div></section><section id="home-lojas" class="shell section"><span class="ey">Vitrines locais</span><h2>Lojas em destaque</h2><div id="storeGrid" class="grid"></div></section><section id="home-servicos" class="shell section"><span class="ey">Profissionais</span><h2>Prestadores de serviços</h2><div class="services">${svc.map(x=>`<div class="service"><span style="font-size:1.5rem">${x[0]}</span><b>${x[1]}</b><span>Encontre profissionais e peça orçamento diretamente.</span></div>`).join('')}</div></section><footer class="shell footer">WDM Shopping · WDM Apps</footer>`;
 const q=document.getElementById('q'),grid=document.getElementById('storeGrid');const draw=()=>{const t=q.value.toLowerCase();grid.innerHTML=stores.filter(s=>`${s[1]} ${s[2]} ${s[5]}`.toLowerCase().includes(t)).map(s=>`<article class="card"><div class="cover" style="background:linear-gradient(135deg,${E(s[4])},#10203a)"><span class="badge">Loja local</span></div><div class="body"><div class="storeline"><div class="avatar">${E(s[3])}</div><div><h3>${E(s[1])}</h3><span class="muted">${E(s[2])}</span></div></div><p>${E(s[5])}</p><div class="meta"><span>Vitrine online</span><a href="#loja/${encodeURIComponent(s[0])}">Visitar →</a></div></div></article>`).join('')||'<div class="note">Nenhuma loja encontrada.</div>'};draw();q.oninput=draw;document.getElementById('go').onclick=draw;if(anchor)setTimeout(()=>document.getElementById(anchor)?.scrollIntoView(),30)
}

async function authPage(reg){
 app.innerHTML=`<div class="authWrap"><section class="auth"><span class="ey">${reg?'Cadastro do lojista':'Área do lojista'}</span><h1>${reg?'Abrir minha loja':'Entrar no painel'}</h1><p class="muted">${reg?'Crie sua conta e sua vitrine online.':'Acesse a loja que você já cadastrou.'}</p><form id="authForm" class="form">${reg?`<div class="two"><div class="field"><label>Seu nome</label><input name="name" required></div><div class="field"><label>Nome do negócio</label><input name="business" required></div></div>`:''}<div class="two"><div class="field"><label>E-mail</label><input name="email" type="email" required></div><div class="field"><label>Senha</label><input name="password" type="password" minlength="6" required></div></div>${reg?`<div class="two"><div class="field"><label>Categoria</label><select name="category"><option>Tecnologia</option><option>Alimentação</option><option>Casa</option><option>Moda</option><option>Beleza</option><option>Serviços</option><option>Outros</option></select></div><div class="field"><label>WhatsApp</label><input id="authPhone" name="phone" inputmode="tel" placeholder="(11) 9 9999-9999"></div></div>`:''}<div id="status" class="status"></div><button class="btn" type="submit">${reg?'Criar conta e loja':'Entrar'}</button></form><p class="muted">${reg?'Já tem cadastro? <a href="#login">Entrar</a>':'Ainda não tem loja? <a href="#cadastro">Cadastrar</a>'}</p></section></div>`;
 if(reg)document.getElementById('authPhone').oninput=e=>e.target.value=phone(e.target.value);
 const form=document.getElementById('authForm'),st=document.getElementById('status');form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form),email=String(f.get('email')).trim().toLowerCase(),pass=String(f.get('password'));st.className='status';st.textContent='';try{if(reg){const cred=await createUserWithEmailAndPassword(auth,email,pass),uid=cred.user.uid;let sid=slug(f.get('business')),base=sid,n=2;try{while((await getDoc(doc(db,'slugs',sid))).exists())sid=base+'-'+n++;const store={ownerId:uid,slug:sid,name:String(f.get('business')).trim(),category:String(f.get('category')),initials:initials(f.get('business')),primary:'#2f7df6',description:'Bem-vindo à nossa vitrine no WDM Shopping.',whatsapp:wd(f.get('phone')),instagram:'',promo:'Confira nossas novidades!',published:true,createdAt:serverTimestamp(),updatedAt:serverTimestamp()};await setDoc(doc(db,'stores',uid),store);await setDoc(doc(db,'slugs',sid),{storeId:uid,ownerId:uid,createdAt:serverTimestamp()});await setDoc(doc(db,'users',uid),{name:String(f.get('name')).trim(),email,storeId:uid,createdAt:serverTimestamp()})}catch(x){await deleteDoc(doc(db,'stores',uid)).catch(()=>{});await deleteDoc(doc(db,'slugs',sid)).catch(()=>{});await deleteUser(cred.user).catch(()=>{});throw x}}else await signInWithEmailAndPassword(auth,email,pass);location.hash='#painel'}catch(x){st.className='status err';st.textContent=msg(x)}}
}

async function panel(){
 if(!auth.currentUser){location.hash='#login';return}
 const subSnap=await getDoc(doc(db,'subscriptions',auth.currentUser.uid)),sub=subSnap.exists()?subSnap.data():null,subStatus=String(sub?.status||'').toLowerCase();
 if(sub?.entitled!==true&&!['active','grace_period'].includes(subStatus)){window.wdmSubscriptionRefresh?.();return}
 const s=await getStore();if(!s){app.innerHTML='<div class="authWrap"><section class="auth"><h1>Loja não encontrada</h1><p class="muted">Confira se o Firestore e as regras já foram configurados.</p></section></div>';return}const ps=await getProducts(s.id,true),url=rid(s);
 app.innerHTML=`<div class="panelWrap"><aside class="side"><div class="brand"><span class="logo">W</span><span>WDM<small>Shopping</small></span></div><nav><a href="#painel">Minha loja</a><a href="#loja/${encodeURIComponent(url)}">Ver vitrine</a><a href="#home">Voltar ao Shopping</a><button id="logout">Sair</button></nav></aside><section><div class="panel"><span class="ey">Área do lojista</span><div class="row"><h1>Gerencie sua loja</h1><a class="btn2" href="#loja/${encodeURIComponent(url)}">Abrir vitrine →</a></div><form id="storeForm" class="form"><div class="two"><div class="field"><label>Nome da loja</label><input name="name" value="${E(s.name)}" required></div><div class="field"><label>Categoria</label><select name="category">${['Tecnologia','Alimentação','Casa','Moda','Beleza','Serviços','Outros'].map(x=>`<option ${x===s.category?'selected':''}>${x}</option>`).join('')}</select></div></div><div class="two"><div class="field"><label>WhatsApp</label><input id="phoneField" name="phone" value="${E(phone(s.whatsapp))}"></div><div class="field"><label>Instagram</label><input name="instagram" value="${E(s.instagram||'')}" placeholder="@minhaloja"></div></div><div class="two"><div class="field"><label>Cor principal</label><input name="primary" type="color" value="${E(s.primary||'#2f7df6')}"></div><div class="field"><label>Endereço da vitrine</label><input value="wdmapps.com.br/shopping/#loja/${E(url)}" readonly></div></div><div class="field"><label>Descrição</label><textarea name="description">${E(s.description||'')}</textarea></div><div class="field"><label>Promoção em destaque</label><textarea name="promo">${E(s.promo||'')}</textarea></div><label><input name="published" type="checkbox" ${s.published!==false?'checked':''}> Loja publicada</label><div id="saveSt" class="status"></div><button class="btn" type="submit">Salvar alterações</button></form></div><div class="panel" style="margin-top:18px"><div class="row"><div><span class="ey">Catálogo</span><h2>Produtos</h2></div><span class="muted">${ps.length} cadastrado(s)</span></div><form id="prodForm" class="form"><input name="id" type="hidden"><div class="two"><div class="field"><label>Produto</label><input name="name" required placeholder="Ex.: Notebook Dell"></div><div class="field"><label>Preço</label><input id="price" name="price" inputmode="numeric" required placeholder="R$ 0,00"></div></div><div class="two"><div class="field"><label>Preço anterior</label><input id="oldPrice" name="oldPrice" inputmode="numeric" placeholder="R$ 0,00"></div><div class="field"><label>Descrição</label><input name="description"></div></div><label><input name="featured" type="checkbox"> Destacar produto</label><label><input name="active" type="checkbox" checked> Produto visível</label><div id="prodSt" class="status"></div><button class="btn" type="submit">Salvar produto</button></form><div id="plist" class="products"></div></div></section></div>`;
 const sf=document.getElementById('storeForm'),pf=document.getElementById('prodForm'),phoneEl=document.getElementById('phoneField'),price=document.getElementById('price'),old=document.getElementById('oldPrice'),save=document.getElementById('saveSt'),pst=document.getElementById('prodSt'),list=document.getElementById('plist');phoneEl.oninput=e=>e.target.value=phone(e.target.value);for(const el of[price,old])el.oninput=e=>e.target.value=D(e.target.value)?money(pm(e.target.value)):'';document.getElementById('logout').onclick=async()=>{await signOut(auth);location.hash='#home'};
 sf.onsubmit=async e=>{e.preventDefault();const f=new FormData(sf),data={name:String(f.get('name')).trim(),category:String(f.get('category')),initials:initials(f.get('name')),whatsapp:wd(f.get('phone')),instagram:String(f.get('instagram')).trim(),primary:String(f.get('primary')),description:String(f.get('description')).trim(),promo:String(f.get('promo')).trim(),published:f.get('published')==='on',updatedAt:serverTimestamp()};try{await updateDoc(doc(db,'stores',s.id),data);save.className='status';save.textContent='Loja salva';setTimeout(()=>save.textContent='',1800)}catch(x){save.className='status err';save.textContent=msg(x)}};
 pf.onsubmit=async e=>{e.preventDefault();const f=new FormData(pf),id=String(f.get('id')||''),data={name:String(f.get('name')).trim(),price:pm(f.get('price')),oldPrice:pm(f.get('oldPrice')),description:String(f.get('description')).trim(),featured:f.get('featured')==='on',active:f.get('active')==='on',updatedAt:serverTimestamp()};if(!data.name||data.price<=0){pst.className='status err';pst.textContent='Informe nome e preço maior que zero.';return}try{const ref=id?doc(db,'stores',s.id,'products',id):doc(collection(db,'stores',s.id,'products'));await setDoc(ref,{...data,...(id?{}:{createdAt:serverTimestamp()})},{merge:true});await panel()}catch(x){pst.className='status err';pst.textContent=msg(x)}};
 const draw=async()=>{const arr=await getProducts(s.id,true);list.innerHTML=arr.length?arr.map(p=>`<div class="prod"><div><b>${E(p.name)} ${p.featured?'⭐':''}</b><span class="old">${p.oldPrice?money(p.oldPrice):''}</span><span class="price">${money(p.price)}</span><div class="muted">${E(p.description||'')}</div></div><div class="prodBtns"><button class="mini" data-edit="${p.id}">Editar</button><button class="mini danger" data-del="${p.id}">Excluir</button></div></div>`).join(''):'<div class="note">Nenhum produto cadastrado ainda.</div>';list.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{await deleteDoc(doc(db,'stores',s.id,'products',b.dataset.del));await draw()});list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=async()=>{const d=await getDoc(doc(db,'stores',s.id,'products',b.dataset.edit));if(!d.exists())return;const p={id:d.id,...d.data()};pf.elements.id.value=p.id;pf.elements.name.value=p.name;price.value=money(p.price);old.value=p.oldPrice?money(p.oldPrice):'';pf.elements.description.value=p.description||'';pf.elements.featured.checked=!!p.featured;pf.elements.active.checked=p.active!==false;pf.scrollIntoView({behavior:'smooth'})})};await draw()
}

async function storePage(id){
 let s=await bySlug(id);if(!s){const x=samples.find(a=>a[0]===id);if(x)s={id:x[0],name:x[1],category:x[2],initials:x[3],primary:x[4],description:x[5],promo:'Vitrine demonstrativa',whatsapp:'',published:true}}
 if(!s){app.innerHTML='<div class="authWrap"><section class="auth"><h1>Loja não encontrada</h1><a class="btn" href="#home">Voltar</a></section></div>';return}if(s.published===false&&auth.currentUser?.uid!==s.ownerId){app.innerHTML='<div class="authWrap"><section class="auth"><h1>Loja indisponível</h1><p class="muted">Esta vitrine está temporariamente oculta.</p><a class="btn" href="#home">Voltar</a></section></div>';return}const ps=await getProducts(s.id),ig=String(s.instagram||'').replace(/^@/,'');
 app.innerHTML=`<section class="shell storeHero" style="--store:${E(s.primary||'#2f7df6')}"><div class="banner"></div><div class="profile"><div class="big">${E(s.initials||'WS')}</div><div><span class="ey">${E(s.category||'Loja')}</span><h1>${E(s.name)}</h1><p class="muted">${E(s.description||'')}</p></div><div class="actions">${ig?`<a class="btn2" target="_blank" rel="noreferrer" href="https://instagram.com/${encodeURIComponent(ig)}">Instagram</a>`:''}${s.whatsapp?`<a class="btn" target="_blank" rel="noreferrer" href="https://wa.me/${wd(s.whatsapp)}?text=${encodeURIComponent('Olá! Vi sua loja no WDM Shopping.')}">WhatsApp</a>`:''}</div></div><div class="promo">${E(s.promo||'Confira nossas novidades!')}</div></section><section class="shell section"><span class="ey">Catálogo</span><h2>Produtos</h2><div class="productGrid">${ps.length?ps.map(p=>`<article class="product"><h3>${E(p.name)} ${p.featured?'⭐':''}</h3><p class="muted">${E(p.description||'')}</p><div>${p.oldPrice?`<span class="old">${money(p.oldPrice)}</span>`:''}<span class="price">${money(p.price)}</span></div>${s.whatsapp?`<a class="wa" target="_blank" rel="noreferrer" href="https://wa.me/${wd(s.whatsapp)}?text=${encodeURIComponent('Olá! Tenho interesse no produto '+p.name+' que vi no WDM Shopping.')}">Pedir no WhatsApp</a>`:''}</article>`).join(''):'<div class="note">Esta loja ainda não cadastrou produtos.</div>'}</div></section><footer class="shell footer">WDM Shopping · WDM Apps</footer>`
}

let busy=false;async function route(){if(busy)return;busy=true;try{nav();const h=(location.hash||'#home').slice(1),[r,id]=h.split('/');if(r==='cadastro')await authPage(true);else if(r==='login')await authPage(false);else if(r==='painel')await panel();else if(r==='loja')await storePage(decodeURIComponent(id||''));else if(r==='home-lojas')await home('home-lojas');else if(r==='home-servicos')await home('home-servicos');else await home()}catch(e){console.error(e);app.innerHTML=`<div class="authWrap"><section class="auth"><h1>Não foi possível carregar</h1><p class="muted">${E(msg(e))}</p><a class="btn" href="#home">Voltar ao início</a></section></div>`}finally{busy=false}}
window.addEventListener('hashchange',route);onAuthStateChanged(auth,()=>route());
