(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const LIB='wdm-sheets-library-v2';
let workbook=null,currentId=null,activeSheet=0,selected='A1',dirty=false,editStart='',undoStack=[],redoStack=[],contextAddr='A1';
const uid=()=>crypto?.randomUUID?.()||('id-'+Date.now()+'-'+Math.random().toString(36).slice(2));
function colName(n){let s='';while(n>=0){s=String.fromCharCode(n%26+65)+s;n=Math.floor(n/26)-1}return s}
function parts(a){const m=/^([A-Z]+)(\d+)$/.exec(String(a).toUpperCase());if(!m)return null;let c=0;for(const ch of m[1])c=c*26+ch.charCodeAt(0)-64;return{c:c-1,r:+m[2]}}
function defFmt(){return{font:'Calibri',size:11,bold:false,italic:false,underline:false,color:'#202622',fill:'#ffffff',align:'left',num:'general',dec:2}}
function newSheet(name){return{id:uid(),name:name||'Planilha1',rows:40,cols:16,cells:{},colWidths:{},rowHeights:{},frozen:true}}
function blankBook(){return{id:uid(),name:'Pasta de trabalho sem título',sheets:[newSheet('Planilha1')],updated:null}}
const sh=()=>workbook.sheets[activeSheet];
function cell(a,create=false){if(!sh().cells[a]&&create)sh().cells[a]={v:'',fmt:defFmt()};return sh().cells[a]||null}
const raw=a=>String(cell(a)?.v??'');
const fmt=a=>({...defFmt(),...(cell(a)?.fmt||{})});
function setRaw(a,v){const c=cell(a,true);c.v=String(v??'');if(!c.fmt)c.fmt=defFmt()}
function markDirty(msg='Alterações não salvas'){dirty=true;$('#saveState').textContent=msg}
function clean(msg='Salvo no navegador'){dirty=false;$('#saveState').textContent=msg}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),1600)}
function lib(){try{const x=JSON.parse(localStorage.getItem(LIB)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
const writeLib=x=>localStorage.setItem(LIB,JSON.stringify(x));
const snapshot=()=>JSON.stringify({workbook,activeSheet,selected});
function pushHistory(){undoStack.push(snapshot());if(undoStack.length>30)undoStack.shift();redoStack=[];syncUndo()}
function restore(s){try{const x=JSON.parse(s);workbook=x.workbook;activeSheet=x.activeSheet||0;selected=x.selected||'A1';$('#bookName').value=workbook.name||'Pasta de trabalho sem título';renderAll();markDirty()}catch{}}
function undo(){if(!undoStack.length)return;redoStack.push(snapshot());restore(undoStack.pop());syncUndo()}
function redo(){if(!redoStack.length)return;undoStack.push(snapshot());restore(redoStack.pop());syncUndo()}
function syncUndo(){$('#undoBtn').disabled=!undoStack.length;$('#redoBtn').disabled=!redoStack.length}
function rangeAddrs(a,b){const p=parts(a),q=parts(b),out=[];if(!p||!q)return out;for(let r=Math.min(p.r,q.r);r<=Math.max(p.r,q.r);r++)for(let c=Math.min(p.c,q.c);c<=Math.max(p.c,q.c);c++)out.push(colName(c)+r);return out}
function scalar(a,seen=new Set()){const v=raw(a).trim();if(v.startsWith('='))return evaluate(v,new Set([...seen,a]));const n=Number(v.replace(',','.'));return Number.isFinite(n)&&v!==''?n:v}
function splitArgs(s){const out=[];let cur='',depth=0,quote=false;for(const ch of s){if(ch==='"')quote=!quote;if(!quote&&ch==='(')depth++;if(!quote&&ch===')')depth--;if(!quote&&depth===0&&ch===';'){out.push(cur.trim());cur=''}else cur+=ch}out.push(cur.trim());return out}
function token(t,seen){t=t.trim();if(/^".*"$/.test(t))return t.slice(1,-1);if(/^[A-Z]+\d+$/i.test(t)){const a=t.toUpperCase();if(seen.has(a))throw Error();return scalar(a,seen)}if(/^-?\d+(?:[.,]\d+)?$/.test(t))return Number(t.replace(',','.'));return expr(t,seen)}
function rangeVals(t,seen){const m=/^([A-Z]+\d+):([A-Z]+\d+)$/i.exec(t.trim());if(!m)return[];return rangeAddrs(m[1].toUpperCase(),m[2].toUpperCase()).map(a=>scalar(a,seen))}
function critMatch(value,crit){crit=String(crit??'').replace(/^"|"$/g,'');const m=/^(<=|>=|<>|=|<|>)(.*)$/.exec(crit);if(!m)return String(value)===crit;let rhs=m[2],lv=Number(value),rv=Number(rhs),a=Number.isFinite(lv)&&Number.isFinite(rv)?lv:String(value),b=Number.isFinite(lv)&&Number.isFinite(rv)?rv:rhs;return m[1]==='>'?a>b:m[1]==='<'?a<b:m[1]==='>='?a>=b:m[1]==='<='?a<=b:m[1]==='<>'?a!=b:a==b}
function condition(s,seen){const m=/(.+?)(<=|>=|<>|=|<|>)(.+)/.exec(s);if(!m)return Boolean(token(s,seen));const a=token(m[1],seen),b=token(m[3],seen),op=m[2];return op==='>'?a>b:op==='<'?a<b:op==='>='?a>=b:op==='<='?a<=b:op==='<>'?a!=b:a==b}
function fn(name,argsText,seen){const args=splitArgs(argsText),n=name.toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''),nums=t=>rangeVals(t,seen).map(Number).filter(Number.isFinite);if(['SOMA','SUM'].includes(n))return nums(args[0]).reduce((a,b)=>a+b,0);if(['MEDIA','AVERAGE'].includes(n)){const x=nums(args[0]);return x.length?x.reduce((a,b)=>a+b,0)/x.length:0}if(['MINIMO','MIN'].includes(n)){const x=nums(args[0]);return x.length?Math.min(...x):0}if(['MAXIMO','MAX'].includes(n)){const x=nums(args[0]);return x.length?Math.max(...x):0}if(['MEDIANA','MEDIAN'].includes(n)){const x=nums(args[0]).sort((a,b)=>a-b);if(!x.length)return 0;const i=Math.floor(x.length/2);return x.length%2?x[i]:(x[i-1]+x[i])/2}if(['CONT.NUM','COUNT','CONTNUM'].includes(n))return nums(args[0]).length;if(['CONT.VALORES','COUNTA','CONTVALORES'].includes(n))return rangeVals(args[0],seen).filter(v=>String(v)!=='').length;if(['ARRED','ROUND'].includes(n)){const v=Number(token(args[0],seen)),d=Number(token(args[1]||'0',seen)),p=10**d;return Math.round(v*p)/p}if(n==='ABS')return Math.abs(Number(token(args[0],seen)));if(['RAIZ','SQRT'].includes(n))return Math.sqrt(Number(token(args[0],seen)));if(['POTENCIA','POWER'].includes(n))return Math.pow(Number(token(args[0],seen)),Number(token(args[1],seen)));if(['HOJE','TODAY'].includes(n))return new Date().toLocaleDateString('pt-BR');if(['SE','IF'].includes(n))return token(condition(args[0],seen)?args[1]:args[2],seen);if(['CONT.SE','COUNTIF','CONTSE'].includes(n)){const x=rangeVals(args[0],seen),c=token(args[1],seen);return x.filter(v=>critMatch(v,c)).length}if(['SOMASE','SUMIF'].includes(n)){const test=rangeVals(args[0],seen),c=token(args[1],seen),sum=args[2]?rangeVals(args[2],seen):test;return test.reduce((acc,v,i)=>acc+(critMatch(v,c)?Number(sum[i])||0:0),0)}throw Error()}
function replaceFns(e,seen){let prev;do{prev=e;e=e.replace(/([A-ZÁÉÍÓÚÇ.]+)\(([^()]*)\)/gi,(all,n,args)=>{try{return JSON.stringify(fn(n,args,seen))}catch{return all}})}while(e!==prev);return e}
function expr(e,seen){e=replaceFns(e,seen);e=e.replace(/\b([A-Z]+\d+)\b/gi,(_,a)=>{a=a.toUpperCase();if(seen.has(a))throw Error();return JSON.stringify(scalar(a,seen))});e=e.replace(/<>/g,'!=').replace(/(?<![<>=!])=(?!=)/g,'==');if(!/^[0-9+\-*/().,<>=! "A-Za-zÀ-ÿ]+$/.test(e))throw Error();return Function('"use strict";return ('+e+')')()}
function evaluate(v,seen=new Set()){try{return expr(v.slice(1).trim(),seen)}catch{return'#ERRO!'}}
function displayValue(a){const v=raw(a);return v.trim().startsWith('=')?evaluate(v,new Set([a])):v}
function formatDisplay(a,v){const f=fmt(a);if(v==='#ERRO!')return v;if(f.num==='currency'){const n=Number(v);return Number.isFinite(n)?n.toLocaleString('pt-BR',{style:'currency',currency:'BRL',minimumFractionDigits:f.dec,maximumFractionDigits:f.dec}):v}if(f.num==='percent'){const n=Number(v);return Number.isFinite(n)?(n*100).toLocaleString('pt-BR',{minimumFractionDigits:f.dec,maximumFractionDigits:f.dec})+'%':v}if(f.num==='number'){const n=Number(v);return Number.isFinite(n)?n.toLocaleString('pt-BR',{minimumFractionDigits:f.dec,maximumFractionDigits:f.dec}):v}return String(v??'')}
function styleCell(td,a){const f=fmt(a),i=td.querySelector('input');td.style.background=f.fill||'#fff';i.style.fontFamily=f.font;i.style.fontSize=f.size+'px';i.style.fontWeight=f.bold?'700':'400';i.style.fontStyle=f.italic?'italic':'normal';i.style.textDecoration=f.underline?'underline':'none';i.style.color=f.color;i.style.textAlign=f.align}
function renderGrid(){const grid=$('#grid');grid.classList.toggle('unfrozen',!sh().frozen);grid.innerHTML='';const top=document.createElement('tr'),corner=document.createElement('th');corner.className='corner';top.appendChild(corner);for(let c=0;c<sh().cols;c++){const th=document.createElement('th');th.className='colhead';th.dataset.col=c;th.textContent=colName(c);th.style.width=(sh().colWidths[c]||100)+'px';th.style.minWidth=th.style.width;const rz=document.createElement('span');rz.className='resize-col';rz.onmousedown=e=>resizeCol(e,c,th);th.appendChild(rz);top.appendChild(th)}grid.appendChild(top);for(let r=1;r<=sh().rows;r++){const tr=document.createElement('tr'),rh=document.createElement('th');rh.className='rowhead';rh.dataset.row=r;rh.textContent=r;rh.style.height=(sh().rowHeights[r]||27)+'px';const rr=document.createElement('span');rr.className='resize-row';rr.onmousedown=e=>resizeRow(e,r,rh);rh.appendChild(rr);tr.appendChild(rh);for(let c=0;c<sh().cols;c++){const a=colName(c)+r,td=document.createElement('td');td.dataset.cell=a;td.style.width=(sh().colWidths[c]||100)+'px';td.style.minWidth=td.style.width;td.style.height=(sh().rowHeights[r]||27)+'px';const input=document.createElement('input');input.dataset.cell=a;input.value=formatDisplay(a,displayValue(a));input.onfocus=()=>{editStart=raw(a);selectCell(a,false);input.value=raw(a)};input.oninput=()=>$('#formulaInput').value=input.value;input.onblur=()=>{if(input.value!==editStart){pushHistory();setRaw(a,input.value);markDirty();recalc()}else input.value=formatDisplay(a,displayValue(a))};input.onkeydown=e=>cellKey(e,a);td.onmousedown=()=>selectCell(a,false);td.oncontextmenu=e=>showContext(e,a);td.appendChild(input);styleCell(td,a);tr.appendChild(td)}grid.appendChild(tr)}selectCell(selected,false);recalc()}
function recalc(){for(const td of $$('#grid td[data-cell]')){const a=td.dataset.cell,i=td.querySelector('input');styleCell(td,a);if(document.activeElement!==i)i.value=formatDisplay(a,displayValue(a))}}
function selectCell(a,focus=false){const p=parts(a);if(!p||p.c<0||p.c>=sh().cols||p.r<1||p.r>sh().rows)return;selected=a;$$('#grid td.selected').forEach(x=>x.classList.remove('selected'));$$('#grid th.active-head').forEach(x=>x.classList.remove('active-head'));const td=$(`#grid td[data-cell="${a}"]`);td?.classList.add('selected');$(`#grid .colhead[data-col="${p.c}"]`)?.classList.add('active-head');$(`#grid .rowhead[data-row="${p.r}"]`)?.classList.add('active-head');$('#nameBox').value=a;$('#formulaInput').value=raw(a);$('#statusRight').textContent=sh().name+' · '+a;syncToolbar();if(focus){const i=td?.querySelector('input');i?.focus();i?.select()}}
function cellKey(e,a){const p=parts(a);if(e.key==='Enter'){e.preventDefault();e.currentTarget.blur();selectCell(colName(p.c)+Math.min(sh().rows,p.r+1),true)}else if(e.key==='Tab'){e.preventDefault();e.currentTarget.blur();selectCell(colName(Math.min(sh().cols-1,p.c+1))+p.r,true)}}
function syncToolbar(){const f=fmt(selected);$('#fontFamily').value=f.font;$('#fontSize').value=String(f.size);$('#fontColor').value=f.color||'#202622';$('#fillColor').value=f.fill||'#ffffff';$('#boldBtn').style.background=f.bold?'#dfeee5':'';$('#italicBtn').style.background=f.italic?'#dfeee5':'';$('#underlineBtn').style.background=f.underline?'#dfeee5':''}
function mutateFmt(fn){pushHistory();const c=cell(selected,true);c.fmt={...defFmt(),...(c.fmt||{})};fn(c.fmt);markDirty();recalc();syncToolbar()}
function resizeCol(e,c,th){e.preventDefault();e.stopPropagation();const x=e.clientX,start=th.getBoundingClientRect().width,move=ev=>{sh().colWidths[c]=Math.max(45,start+ev.clientX-x);renderGrid()},up=()=>{document.removeEventListener('mousemove',move);document.removeEventListener('mouseup',up);markDirty()};document.addEventListener('mousemove',move);document.addEventListener('mouseup',up)}
function resizeRow(e,r,th){e.preventDefault();e.stopPropagation();const y=e.clientY,start=th.getBoundingClientRect().height,move=ev=>{sh().rowHeights[r]=Math.max(20,start+ev.clientY-y);renderGrid()},up=()=>{document.removeEventListener('mousemove',move);document.removeEventListener('mouseup',up);markDirty()};document.addEventListener('mousemove',move);document.addEventListener('mouseup',up)}
function shiftRows(start,delta){const out={};for(const [a,c] of Object.entries(sh().cells)){const p=parts(a);if(p.r>=start){const nr=p.r+delta;if(nr>=1)out[colName(p.c)+nr]=c}else out[a]=c}sh().cells=out}
function shiftCols(start,delta){const out={};for(const [a,c] of Object.entries(sh().cells)){const p=parts(a);if(p.c>=start){const nc=p.c+delta;if(nc>=0)out[colName(nc)+p.r]=c}else out[a]=c}sh().cells=out}
function structure(act){const p=parts(contextAddr||selected);pushHistory();if(act==='insertRowAbove'){shiftRows(p.r,1);sh().rows++}if(act==='insertRowBelow'){shiftRows(p.r+1,1);sh().rows++}if(act==='deleteRow'){shiftRows(p.r+1,-1);sh().rows=Math.max(1,sh().rows-1)}if(act==='insertColLeft'){shiftCols(p.c,1);sh().cols++}if(act==='insertColRight'){shiftCols(p.c+1,1);sh().cols++}if(act==='deleteCol'){shiftCols(p.c+1,-1);sh().cols=Math.max(1,sh().cols-1)}if(act==='clearCell')setRaw(contextAddr,'');markDirty();selected='A1';renderGrid()}
function showContext(e,a){e.preventDefault();contextAddr=a;selectCell(a,false);const m=$('#context');m.style.left=Math.min(e.clientX,innerWidth-205)+'px';m.style.top=Math.min(e.clientY,innerHeight-250)+'px';m.classList.add('show')}
function renderTabs(){const bar=$('#sheetBar');bar.querySelectorAll('.sheet-tab').forEach(x=>x.remove());workbook.sheets.forEach((s,i)=>{const b=document.createElement('button');b.className='sheet-tab'+(i===activeSheet?' active':'');b.textContent=s.name;b.onclick=()=>{activeSheet=i;selected='A1';renderAll()};b.ondblclick=()=>renameSheet(i);b.oncontextmenu=e=>{e.preventDefault();if(workbook.sheets.length===1)return toast('É preciso manter uma planilha');if(confirm('Excluir a planilha "'+s.name+'"?')){pushHistory();workbook.sheets.splice(i,1);activeSheet=Math.max(0,Math.min(activeSheet,workbook.sheets.length-1));markDirty();renderAll()}};bar.appendChild(b)})}
function renameSheet(i){const n=prompt('Novo nome da planilha:',workbook.sheets[i].name);if(!n)return;pushHistory();workbook.sheets[i].name=n.slice(0,31);markDirty();renderTabs()}
function renderAll(){$('#bookName').value=workbook.name;renderTabs();renderGrid();$('#freezeBtn').textContent=sh().frozen?'❄ Cabeçalhos: ON':'❄ Cabeçalhos: OFF';syncUndo()}
const canDiscard=()=>!dirty||confirm('Há alterações não salvas. Deseja continuar sem salvar?');
function newBook(){if(!canDiscard())return;workbook=blankBook();currentId=null;activeSheet=0;selected='A1';undoStack=[];redoStack=[];clean('Nova pasta de trabalho');renderAll()}
function saveBrowser(){workbook.name=$('#bookName').value.trim()||'Pasta de trabalho sem título';workbook.updated=new Date().toISOString();if(!currentId)currentId=uid();workbook.id=currentId;const items=lib(),i=items.findIndex(x=>x.id===currentId),copy=JSON.parse(JSON.stringify(workbook));if(i>=0)items[i]=copy;else items.unshift(copy);writeLib(items);clean();renderSaved();toast('Pasta salva neste navegador')}
function renderSaved(){const list=$('#savedList'),items=lib().sort((a,b)=>String(b.updated).localeCompare(String(a.updated)));list.innerHTML='';if(!items.length){list.innerHTML='<div class="empty">Nenhuma pasta salva ainda.</div>';return}items.forEach(w=>{const row=document.createElement('div');row.className='saved-item';const main=document.createElement('button');main.className='saved-main';main.innerHTML='<strong></strong><span></span>';main.querySelector('strong').textContent=w.name||'Pasta sem título';main.querySelector('span').textContent=(w.sheets?.length||1)+' planilha(s) · '+(w.updated?new Date(w.updated).toLocaleString('pt-BR'):'');main.onclick=()=>{if(!canDiscard())return;workbook=JSON.parse(JSON.stringify(w));currentId=w.id;activeSheet=0;selected='A1';undoStack=[];redoStack=[];clean('Aberto do navegador');$('#savedModal').classList.remove('show');renderAll()};const del=document.createElement('button');del.className='delete-saved';del.textContent='Excluir';del.onclick=e=>{e.stopPropagation();if(confirm('Excluir "'+(w.name||'Pasta')+'"?')){writeLib(lib().filter(x=>x.id!==w.id));renderSaved()}};row.append(main,del);list.appendChild(row)})}
function xlsxFormula(v){return v.slice(1).replace(/\bSOMA\b/gi,'SUM').replace(/\bM[ÉE]DIA\b/gi,'AVERAGE').replace(/\bM[ÍI]NIMO\b/gi,'MIN').replace(/\bM[ÁA]XIMO\b/gi,'MAX').replace(/\bMEDIANA\b/gi,'MEDIAN').replace(/\bCONT\.N[ÚU]M\b/gi,'COUNT').replace(/\bCONT\.VALORES\b/gi,'COUNTA').replace(/\bCONT\.SE\b/gi,'COUNTIF').replace(/\bSOMASE\b/gi,'SUMIF').replace(/\bARRED\b/gi,'ROUND').replace(/\bRAIZ\b/gi,'SQRT').replace(/\bPOT[ÊE]NCIA\b/gi,'POWER').replace(/\bHOJE\b/gi,'TODAY').replace(/\bSE\b/gi,'IF').replace(/;/g,',')}
function exportXlsx(){if(!window.XLSX)return alert('Biblioteca do Excel não carregou.');const wb=XLSX.utils.book_new();for(const s of workbook.sheets){const ws={};let maxR=1,maxC=0;for(const [a,c] of Object.entries(s.cells)){const p=parts(a);maxR=Math.max(maxR,p.r);maxC=Math.max(maxC,p.c);const v=String(c.v??'');if(v.startsWith('='))ws[a]={t:'n',f:xlsxFormula(v)};else{const n=Number(v.replace(',','.'));ws[a]=Number.isFinite(n)&&v.trim()!==''?{t:'n',v:n}:{t:'s',v}}}ws['!ref']='A1:'+colName(Math.max(maxC,s.cols-1))+Math.max(maxR,s.rows);ws['!cols']=Array.from({length:s.cols},(_,i)=>({wch:Math.max(5,Math.round((s.colWidths[i]||100)/7))}));XLSX.utils.book_append_sheet(wb,ws,s.name.slice(0,31)||'Planilha')}const name=($('#bookName').value||'Pasta de trabalho').replace(/[\\/:*?"<>|]+/g,'-');XLSX.writeFile(wb,name+'.xlsx');toast('Arquivo .xlsx gerado')}
async function importFile(file){if(!file||!canDiscard())return;try{let sheets=[];if(/\.csv$/i.test(file.name)){const text=(await file.text()).replace(/^\ufeff/,'');const d=text.split(/\r?\n/).some(x=>x.includes(';'))?';':',';const s=newSheet('Planilha1');text.split(/\r?\n/).forEach((line,r)=>line.split(d).forEach((v,c)=>{if(v!=='')s.cells[colName(c)+(r+1)]={v:v.replace(/^"|"$/g,''),fmt:defFmt()}}));sheets=[s]}else{const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellFormula:true});sheets=wb.SheetNames.map(n=>{const ws=wb.Sheets[n],s=newSheet(n),rg=XLSX.utils.decode_range(ws['!ref']||'A1:A1');s.rows=Math.max(40,rg.e.r+1);s.cols=Math.max(16,rg.e.c+1);for(let r=rg.s.r;r<=rg.e.r;r++)for(let c=rg.s.c;c<=rg.e.c;c++){const a=XLSX.utils.encode_cell({r,c}),x=ws[a];if(x){const v=x.f?'='+x.f:String(x.w??x.v??'');s.cells[colName(c)+(r+1)]={v,fmt:defFmt()}}}return s})}workbook={id:uid(),name:file.name.replace(/\.[^.]+$/,''),sheets,updated:null};currentId=null;activeSheet=0;selected='A1';undoStack=[];redoStack=[];dirty=true;$('#saveState').textContent='Arquivo aberto · não salvo';renderAll()}catch(e){console.error(e);alert('Não foi possível abrir esse arquivo.')}}
$('#boldBtn').onclick=()=>mutateFmt(f=>f.bold=!f.bold);$('#italicBtn').onclick=()=>mutateFmt(f=>f.italic=!f.italic);$('#underlineBtn').onclick=()=>mutateFmt(f=>f.underline=!f.underline);$('#fontFamily').onchange=e=>mutateFmt(f=>f.font=e.target.value);$('#fontSize').onchange=e=>mutateFmt(f=>f.size=Number(e.target.value));$('#fontColor').oninput=e=>mutateFmt(f=>f.color=e.target.value);$('#fillColor').oninput=e=>mutateFmt(f=>f.fill=e.target.value);$$('[data-align]').forEach(b=>b.onclick=()=>mutateFmt(f=>f.align=b.dataset.align));$('#currencyBtn').onclick=()=>mutateFmt(f=>f.num='currency');$('#percentBtn').onclick=()=>mutateFmt(f=>f.num='percent');$('#numberBtn').onclick=()=>mutateFmt(f=>f.num='number');$('#decDown').onclick=()=>mutateFmt(f=>f.dec=Math.max(0,(f.dec??2)-1));$('#decUp').onclick=()=>mutateFmt(f=>f.dec=Math.min(8,(f.dec??2)+1));$('#clearFormat').onclick=()=>mutateFmt(f=>Object.assign(f,defFmt()));
$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;$('#newBook').onclick=newBook;$('#saveBrowser').onclick=saveBrowser;$('#openSaved').onclick=()=>{renderSaved();$('#savedModal').classList.add('show')};$('#closeModal').onclick=()=>$('#savedModal').classList.remove('show');$('#savedModal').onclick=e=>{if(e.target.id==='savedModal')e.currentTarget.classList.remove('show')};$('#openFile').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=async e=>{await importFile(e.target.files?.[0]);e.target.value=''};$('#exportXlsx').onclick=exportXlsx;$('#bookName').oninput=e=>{workbook.name=e.target.value;markDirty()};
$('#addSheet').onclick=()=>{pushHistory();let n=1,name;do{name='Planilha'+n++}while(workbook.sheets.some(s=>s.name===name));workbook.sheets.push(newSheet(name));activeSheet=workbook.sheets.length-1;selected='A1';markDirty();renderAll()};$('#addRowBtn').onclick=()=>{pushHistory();sh().rows+=5;markDirty();renderGrid()};$('#addColBtn').onclick=()=>{pushHistory();sh().cols+=3;markDirty();renderGrid()};$('#freezeBtn').onclick=()=>{pushHistory();sh().frozen=!sh().frozen;markDirty();renderAll()};$$('.formula-example').forEach(b=>b.onclick=()=>{pushHistory();setRaw(selected,b.dataset.formula);markDirty();recalc();$('#formulaInput').value=b.dataset.formula});
$('#formulaInput').onfocus=()=>editStart=raw(selected);$('#formulaInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();if(e.target.value!==editStart){pushHistory();setRaw(selected,e.target.value);markDirty();recalc();selectCell(selected,true)}}};$('#formulaInput').onchange=e=>{if(e.target.value!==editStart){pushHistory();setRaw(selected,e.target.value);markDirty();recalc()}};$('#nameBox').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();selectCell(e.target.value.toUpperCase(),true)}};$('#nameBox').onchange=e=>selectCell(e.target.value.toUpperCase(),true);
$$('.ribbon-tabs button').forEach(b=>b.onclick=()=>{$$('.ribbon-tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('[data-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.panel!==b.dataset.tab))});document.addEventListener('click',()=>$('#context').classList.remove('show'));$$('#context [data-act]').forEach(b=>b.onclick=e=>{e.stopPropagation();$('#context').classList.remove('show');structure(b.dataset.act)});
document.addEventListener('keydown',e=>{if(!(e.ctrlKey||e.metaKey))return;const k=e.key.toLowerCase();if(k==='s'){e.preventDefault();saveBrowser()}else if(k==='n'){e.preventDefault();newBook()}else if(k==='o'){e.preventDefault();$('#openSaved').click()}else if(k==='z'){e.preventDefault();undo()}else if(k==='y'){e.preventDefault();redo()}});document.addEventListener('copy',e=>{if(!selected)return;e.clipboardData?.setData('text/plain',raw(selected));e.preventDefault()});document.addEventListener('cut',e=>{if(!selected)return;e.clipboardData?.setData('text/plain',raw(selected));pushHistory();setRaw(selected,'');markDirty();recalc();e.preventDefault()});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
workbook=blankBook();renderAll();clean('Nova pasta de trabalho');
})();